config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "guestbooks#show", as: :authenticated_root
  end

  root "static_pages#home"

  resources :guestbooks, only: %w[show] do
    resources :messages, only: %w[new create destroy] do
      member do
        post 'publish'
      end
    end
  end

  get "/:username", to: "guestbooks#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guestbook.rb
class Guestbook < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :guestbook

  scope :published, -> { where(published: true) }
  scope :incoming, -> { where(published: false) }

  def incoming?
    !published
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_one :guestbook

  after_create :create_guestbook

  def create_guestbook
    Guestbook.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guestbooks_controller.rb
class GuestbooksController < ApplicationController
  # before_action :authenticate_user!

  def show
    if username = params[:username]
      @guestbook = User.friendly.find(username).guestbook
    else
      @guestbook = current_user.guestbook
    end

    @message = @guestbook.messages.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_guestbook
  before_action :set_message, only: %i[publish destroy]

  def create
    @message = @guestbook.messages.new(message_params)

    if @message.save
      redirect_to "/#{@guestbook.user.username}",
                  notice: "Message sent! Your message will appear here if #{@guestbook.user.username} publishes it."
    else
      redirect_to "/#{@guestbook.user.username}", status: :unprocessable_entity
    end
  end

  def publish
    @message.update(published: true)
    redirect_to "/#{@guestbook.user.username}", notice: 'Message published.'
  end

  def destroy
    @message.destroy
    redirect_to "/#{@guestbook.user.username}", notice: 'Message deleted.', status: :see_other
  end

  private

  def set_guestbook
    @guestbook = Guestbook.find(params[:guestbook_id])
  end

  def set_message
    @message = @guestbook.messages.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guestbooks_helper.rb
module GuestbooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guestbooks/_form.html.erb
<%= form_with(model: guestbook) do |form| %>
  <% if guestbook.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guestbook.errors.count, "error") %> prohibited this guestbook from being saved:</h2>

      <ul>
        <% guestbook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guestbooks/edit.html.erb
<h1>Editing guestbook</h1>

<%= render "form", guestbook: @guestbook %>

<br>

<div>
  <%= link_to "Show this guestbook", @guestbook %> |
  <%= link_to "Back to guestbooks", guestbooks_path %>
</div>

app/views/guestbooks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guestbooks</h1>

<div id="guestbooks">
  <% @guestbooks.each do |guestbook| %>
    <%= render guestbook %>
    <p>
      <%= link_to "Show this guestbook", guestbook %>
    </p>
  <% end %>
</div>

<%= link_to "New guestbook", new_guestbook_path %>

app/views/guestbooks/new.html.erb
<h1>New guestbook</h1>

<%= render "form", guestbook: @guestbook %>

<br>

<div>
  <%= link_to "Back to guestbooks", guestbooks_path %>
</div>

app/views/guestbooks/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @guestbook.user == current_user %>
  <% if @guestbook.messages.incoming.any? %>
    <h3>incoming messages:</h3>
    <%= render @guestbook.messages.incoming.order(created_at: :desc) %>
  <% end %>
<% else %>
  <div class="message-form">
    <%= render "messages/form", guestbook: @guestbook, message: @message %>
  </div>
<% end %>

<% if @guestbook.user == current_user %>
  <h3>published messages:</h3>
<% end %>
<%= render @guestbook.messages.published.order(created_at: :desc) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>simple guestbooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: [guestbook, message]) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit "Send message", class: "message-button" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="message" id="<%= dom_id message %>">
  <span class="username"><%= message.name %></span>:
  <p><%= message.content %></p>
  <p class="message-date"><%= message.created_at.in_time_zone(session[:timezone]).strftime('%B %d, %Y at %I:%M %p') %></p>

  <% if message.guestbook.user == current_user %>
    <% if message.incoming? %>
      <%= button_to "publish", publish_guestbook_message_path(@guestbook, message), class: "button" %> &middot;
    <% end %>
    <%= button_to "delete", guestbook_message_path(@guestbook, message), method: :delete, class: "button" %>
  <% end %>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/shared/_nav.html.erb
<nav>
  <% if signed_in? %>
    <%= link_to "my guestbook", current_user.username %>
    &middot; <%= button_to "log out", destroy_user_session_path, method: :delete, class: "button" %>
  <% else %>
    <%= link_to "home", root_path %>
    &middot; <%= link_to "log in", new_user_session_path %>
    &middot; <%= link_to "sign up", new_user_registration_path %>
  <% end %>
</nav>

app/views/static_pages/home.html.erb
<h1>simple guestbooks</h1>
<p>simple guestbooks for u n me :^)</p>